"""Assemble exactly the files a Hugging Face Space needs into a folder you upload yourself.

Usage::

    python -m api.stage_space --target docker                           # -> build/hf_space_docker/
    python -m api.stage_space --target gradio --sdk-version 5.49.1      # -> build/hf_space_gradio/

Then (you run this): ``hf upload <user>/<space> build/hf_space_docker . --repo-type=space``

Why a staging folder instead of pushing the repo: the Space repo must have
its own README (with the Space's YAML header), and only an **allowlist** of
files is copied - code, the knowledge base, the lock file, the Dockerfile.
``.env``, data, models, notebooks and results never reach the Space. The
staged folder is scanned with the project's secret scanner
(``githooks/check_secrets.py``) and staging fails if anything key-shaped is found.
"""
from __future__ import annotations

import argparse
import importlib.util
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MARKER = ".staged-by-stage-space"

COMMON_FILES = ["api/artifacts.lock.json", "data/knowledge_base/scam_patterns.json"]
COMMON_TREES = ["api", "src"]
DOCKER_FILES = {"Dockerfile": "Dockerfile", ".dockerignore": ".dockerignore",
                "requirements-api.txt": "requirements-api.txt", "deploy/hf_space_docker/README.md": "README.md"}
GRADIO_FILES = {"deploy/hf_space_gradio/app.py": "app.py"}
# Pinned by the Gradio SDK itself on that route; our pins could conflict with it.
GRADIO_PROVIDED = {"fastapi", "starlette", "uvicorn", "python-multipart", "httpx", "huggingface_hub", "pydantic"}


def _copy_tree(src: Path, dst: Path) -> None:
    for path in src.rglob("*.py"):
        if "__pycache__" in path.parts:
            continue
        target = dst / path.relative_to(ROOT)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, target)


def gradio_requirements(api_requirements: str) -> str:
    """requirements-api.txt adapted for the Gradio SDK: no CPU-wheel suffixes, no Gradio-owned pins."""
    out = ["# Generated by api/stage_space.py from requirements-api.txt for the Gradio/ZeroGPU route.",
           "# fastapi/starlette/uvicorn/pydantic/httpx/huggingface_hub/python-multipart come with the",
           "# Gradio SDK; torch/torchvision are left unpinned so the ZeroGPU runtime's supported build is used."]
    for line in api_requirements.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        name = re.split(r"[=<>\s#]", stripped, maxsplit=1)[0]
        if name in GRADIO_PROVIDED:
            continue
        if name in {"torch", "torchvision"}:
            out.append(name)
            continue
        out.append(stripped.split("#", 1)[0].strip())
    out.append("spaces")
    return "\n".join(out) + "\n"


def _load_secret_scanner():
    spec = importlib.util.spec_from_file_location("check_secrets", ROOT / "githooks" / "check_secrets.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # type: ignore[union-attr]
    return module


def scan_for_secrets(folder: Path) -> list[tuple[str, int, str]]:
    """Findings (path, line, kind) for key-shaped strings or forbidden files. Values are never returned."""
    scanner = _load_secret_scanner()
    findings = []
    for path in sorted(folder.rglob("*")):
        if path.is_file() and path.name != MARKER:
            rel = path.relative_to(folder).as_posix()
            findings += scanner.scan_bytes(rel, path.read_bytes())
    return findings


def stage(target: str, out_dir: Path, sdk_version: str | None = None) -> list[Path]:
    """Create ``out_dir`` with the Space files for ``target`` ("docker" or "gradio")."""
    if target == "gradio" and not sdk_version:
        raise ValueError("--sdk-version is required for the gradio target (copy it from the README "
                         "Hugging Face generated when you created the Space)")
    if out_dir.exists():
        if not (out_dir / MARKER).exists():
            raise FileExistsError(f"{out_dir} exists and was not created by this script; refusing to delete it")
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)
    (out_dir / MARKER).write_text("created by python -m api.stage_space; safe to delete\n", encoding="utf-8")

    for tree in COMMON_TREES:
        _copy_tree(ROOT / tree, out_dir)
    for rel in COMMON_FILES:
        (out_dir / rel).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(ROOT / rel, out_dir / rel)
    if target == "docker":
        for src, dst in DOCKER_FILES.items():
            shutil.copy2(ROOT / src, out_dir / dst)
    else:
        for src, dst in GRADIO_FILES.items():
            shutil.copy2(ROOT / src, out_dir / dst)
        readme = (ROOT / "deploy/hf_space_gradio/README.md").read_text(encoding="utf-8")
        (out_dir / "README.md").write_text(readme.replace("{SDK_VERSION}", sdk_version), encoding="utf-8")
        api_reqs = (ROOT / "requirements-api.txt").read_text(encoding="utf-8")
        (out_dir / "requirements.txt").write_text(gradio_requirements(api_reqs), encoding="utf-8")

    findings = scan_for_secrets(out_dir)
    if findings:
        shutil.rmtree(out_dir)
        details = "; ".join(f"{p}:{n} ({kind})" for p, n, kind in findings)
        raise RuntimeError(f"secret scan failed, staging folder removed: {details}")
    return sorted(p for p in out_dir.rglob("*") if p.is_file() and p.name != MARKER)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Stage files for a Hugging Face Space upload.")
    parser.add_argument("--target", choices=["docker", "gradio"], required=True)
    parser.add_argument("--out", type=Path, default=None, help="Default: build/hf_space_<target>")
    parser.add_argument("--sdk-version", help="Gradio SDK version (gradio target only)")
    args = parser.parse_args(argv)
    out_dir = args.out or ROOT / "build" / f"hf_space_{args.target}"
    files = stage(args.target, out_dir, args.sdk_version)
    total = sum(p.stat().st_size for p in files)
    print(f"Staged {len(files)} files ({total / 1024:.0f} KB) in {out_dir} - secret scan clean.")
    for p in files:
        print(f"  {p.relative_to(out_dir).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
